import { Product } from "./types";

export const products: Product[] = [
  {
    id: "cl-01",
    name: "Kraft klamshell burger qutisi",
    category: "Klamshell qutilar",
    price: 780,
    isNew: true,
    unit: "dona",
    packSize: 50,
    image: "clamshell",
    badges: ["Biologik chiriydigan", "Yog'ga chidamli"],
    material: "Kraft karton, 350 gsm",
    sizes: ["S — 12×12 sm", "M — 15×15 sm", "L — 18×18 sm"],
    description:
      "Bitta qo'l bilan yopiladigan qulay qopqoq, ichki qatlami yog' va namlikka chidamli. Burger, hot-dog va shaurma uchun ideal.",
    code: "FP-CL-101"
  },
  {
    id: "cl-02",
    name: "Sendvich uchun kraft quti",
    category: "Klamshell qutilar",
    price: 620,
    unit: "dona",
    packSize: 50,
    image: "clamshell",
    badges: ["Qayta ishlanadigan"],
    material: "Kraft karton, 300 gsm",
    sizes: ["14×10 sm"],
    description: "Yupqa profil, shtabellash uchun qulay — yetkazib berish kuryerlari uchun eng ixcham variant.",
    code: "FP-CL-102"
  },
  {
    id: "cup-01",
    name: "Bir martalik qog'oz stakan (issiq)",
    category: "Stakanlar",
    price: 340,
    isNew: true,
    unit: "dona",
    packSize: 100,
    image: "cup",
    badges: ["Ikki qatlamli", "70°C gacha chidamli"],
    material: "Qog'oz + PE qatlam",
    sizes: ["200 ml", "300 ml", "400 ml"],
    description: "Choy, qahva va issiq ichimliklar uchun. Qo'lni kuydirmaydigan qo'shimcha qatlam bilan.",
    code: "FP-CP-201"
  },
  {
    id: "cup-02",
    name: "Sovuq ichimliklar uchun PET stakan",
    category: "Stakanlar",
    price: 410,
    unit: "dona",
    packSize: 100,
    image: "cup",
    badges: ["Shaffof", "Qopqoqli"],
    material: "PET plastik",
    sizes: ["350 ml", "500 ml", "700 ml"],
    description: "Limonad, milkshake va sovuq kofe uchun tiniq, mustahkam devorli stakan, qopqoq va nay bilan birga.",
    code: "FP-CP-202"
  },
  {
    id: "pz-01",
    name: "Pitsa qutisi (gofra karton)",
    category: "Pitsa qutilari",
    price: 1450,
    oldPrice: 1780,
    unit: "dona",
    packSize: 50,
    image: "pizza",
    badges: ["Havo teshiklari bor", "Mustahkam"],
    material: "3 qatlamli gofra karton",
    sizes: ["26 sm", "30 sm", "33 sm", "40 sm"],
    description: "Bug'ni chiqaruvchi teshiklar pitsa asosini mo'rt saqlaydi, tashish paytida shaklini yo'qotmaydi.",
    code: "FP-PZ-301"
  },
  {
    id: "sl-01",
    name: "Salat va lag'mon uchun deli idish",
    category: "Salat idishlari",
    price: 590,
    unit: "dona",
    packSize: 50,
    image: "deli",
    badges: ["Sizib chiqmaydigan qopqoq", "Mikroto'lqinli pechga mos"],
    material: "PP plastik, shaffof qopqoq",
    sizes: ["500 ml", "750 ml", "1000 ml"],
    description: "Salat, osh, lag'mon va sho'rvalar uchun germetik qopqoqli, isitishga chidamli idish.",
    code: "FP-SL-401"
  },
  {
    id: "sl-02",
    name: "Osh/plov uchun qopqoqli konteyner",
    category: "Salat idishlari",
    price: 540,
    unit: "dona",
    packSize: 50,
    image: "deli",
    badges: ["Moyga chidamli"],
    material: "Alyuminiy folga + karton qopqoq",
    sizes: ["650 ml", "900 ml"],
    description: "Issiq taomlarni uzoq vaqt saqlaydi, pechda qizdirish mumkin — dostavka xizmatlari uchun sinovdan o'tgan.",
    code: "FP-SL-402"
  },
  {
    id: "bg-01",
    name: "Kraft paket (qo'lchali)",
    category: "Kraft paketlar",
    price: 480,
    isNew: true,
    unit: "dona",
    packSize: 100,
    image: "bag",
    badges: ["Qattiq tutqich", "Brendlash mumkin"],
    material: "Kraft qog'oz, 120 gsm",
    sizes: ["S", "M", "L"],
    description: "Fast-food va dostavka buyurtmalarini olib ketish uchun mustahkam qo'lchali paket, logotip bosish mumkin.",
    code: "FP-BG-501"
  },
  {
    id: "bg-02",
    name: "Somsa/fast-food uchun qog'oz qadoq",
    category: "Kraft paketlar",
    price: 210,
    unit: "dona",
    packSize: 100,
    image: "bag",
    badges: ["Yog' o'tkazmaydi"],
    material: "Pergament qog'oz",
    sizes: ["20×20 sm"],
    description: "Somsa, pirojkina va boshqa yog'li mahsulotlarni o'rash uchun pergament qog'oz varag'i.",
    code: "FP-BG-502"
  },
  {
    id: "ut-01",
    name: "Yog'och asboblar to'plami",
    category: "Asboblar va sous",
    price: 260,
    oldPrice: 320,
    unit: "to'plam",
    packSize: 100,
    image: "cutlery",
    badges: ["100% biologik", "Salfetka bilan"],
    material: "Qayin yog'ochi",
    sizes: ["Vilka + qoshiq + salfetka"],
    description: "Plastiksiz muqobil — vilka, qoshiq va salfetkadan iborat individual o'ralgan to'plam.",
    code: "FP-UT-601"
  },
  {
    id: "ut-02",
    name: "Sous uchun kichik idishcha",
    category: "Asboblar va sous",
    price: 90,
    unit: "dona",
    packSize: 200,
    image: "sauce",
    badges: ["Sizib chiqmaydi"],
    material: "PP plastik + qopqoq",
    sizes: ["30 ml", "60 ml"],
    description: "Ketchup, mayonez va milliy souslar uchun qopqoqli kichik idishcha, avtomat dozatorlarga mos.",
    code: "FP-UT-602"
  },
  {
    id: "th-01",
    name: "Termo konteyner (dostavka uchun)",
    category: "Termo konteynerlar",
    price: 3200,
    oldPrice: 3850,
    unit: "dona",
    packSize: 10,
    image: "thermo",
    badges: ["4 soatgacha issiq saqlaydi"],
    material: "EPP ko'pik + kraft qoplama",
    sizes: ["8 L", "15 L", "25 L"],
    description: "Kuryer sumkalari va velosipedlar uchun issiqlikni uzoq saqlaydigan qattiq korpusli konteyner.",
    code: "FP-TH-701"
  }
];

export const categories = [
  "Barchasi",
  "Klamshell qutilar",
  "Stakanlar",
  "Pitsa qutilari",
  "Salat idishlari",
  "Kraft paketlar",
  "Asboblar va sous",
  "Termo konteynerlar"
] as const;
